import getEnv from "../utils/getEnv";

const appConfig = {
  NODE_ENV: getEnv("NODE_ENV"),
  PORT: getEnv("PORT"),
  BASE_PATH: getEnv("BASE_PATH"),
  LOCAL_DATABASE_URL: getEnv("LOCAL_DATABASE_URL"),
  DATABASE_URL: getEnv("DATABASE_URL"),
  CLOUDINARY_API_KEY: getEnv("CLOUDINARY_API_KEY"),
  CLOUDINARY_API_SECRET: getEnv("CLOUDINARY_API_SECRET"),
  CLOUDINARY_CLOUD_NAME: getEnv("CLOUDINARY_CLOUD_NAME"),
  JWT_ACCESS_TOKEN_SECRET: getEnv("JWT_ACCESS_TOKEN_SECRET"),
  JWT_ACCESS_TOKEN_EXPIRY: getEnv("JWT_ACCESS_TOKEN_EXPIRY"),
  JWT_REFRESH_TOKEN_SECRET: getEnv("JWT_REFRESH_TOKEN_SECRET"),
  JWT_REFRESH_TOKEN_EXPIRY: getEnv("JWT_REFRESH_TOKEN_EXPIRY"),
  JWT_COOKIE_NAME: getEnv("JWT_COOKIE_NAME"),
};

export default appConfig;
